### ISSUE TITLE
Switch from tape to jest?

### ISSUE THREAD

**Issue by bali182** [sdgluck/mewt#10]
Again just an idea, but with tape it seems you can't create tests inside a `test`. Also it's not the easiest to read the output this way.

Facebook's [jest](https://facebook.github.io/jest/) allows testing with the same ease (no other libs needed, also almost no configuration) and has a bunch of nice features, like very readable output, watching file changes and intelligently running relevant tests, and probably a lot more I don't know about.

Here is an example of how it looks like https://travis-ci.org/healthiers/mini-dash/jobs/212319390

Also the error reporting is very nice, tells you clearly what exactly went wrong and where, no more, no less.

Would you consider a switch? Feel free to close if not :)

**Comment by sdgluck** [comment]
Sure, I've no particular allegiance to tape. I've used jest in [kasia](https://github.com/outlandishideas/kasia) and agree that it is very nice 😄

**Comment by bali182** [comment]
#16 makes this happen
