### ISSUE TITLE
Add linting (eslint)

### ISSUE THREAD

**Issue by bali182** [sdgluck/mewt#24]
Just an idea (not sure how useful, since the whole codebase fits on one screen 😄), but adding some linting could prevent some accidental mistakes, like unused variables and such.

**Comment by sdgluck** [comment]
Sounds good to me. I use `standard` in a number of my other projects - what do you think?

**Comment by bali182** [comment]
Sounds good! I once sat down, read through all the options and picked the ones I liked. Didn't know eslint configs were composable using "extends"... Oops

**Comment by bali182** [comment]
#25

**Comment by sdgluck** [comment]
Fixed in #25
