### ISSUE TITLE
Not throwing on destructive array methods

### ISSUE THREAD

**Issue by sscotth** [sdgluck/mewt#26]
```js
const a = mewt([])
a.push('foo')
// [1, Proxy]
a.length
// 0
```

**Comment by sdgluck** [comment]
Can you explain this a bit more. Is the example you have shared not the expected behaviour?

**Comment by sscotth** [comment]
When you use the bracket or dot notation to change an object you get an error thrown.

```js
const a = mewt([])
a[0] = 'foo'
// Uncaught Error: array is immutable
```

A similar error should be thrown for the mutable methods. Otherwise it simply fails silently.

**Comment by bali182** [comment]
But we have a test for this: https://github.com/sdgluck/mewt/blob/master/test.js#L56. Or you mean that this happens if in the mewted array the index doesn't exist?

**Comment by sscotth** [comment]
The test is above using the property accessors notation, there is no test using a destructive array method.

This test would currently fail:
```js
it('should throw on destructive method', () => {
  const a = mewt([])
  expect(() => a.push('Lodger')).toThrowError(/immutable/)
})
```

**Comment by bali182** [comment]
`push` returns a new mewted array (mewted is a thing now) and the return value of `push`: https://github.com/sdgluck/mewt/blob/master/test.js#L122. 

It achieves this by first cloning then pushing then mewting. I still don't see the problem. 

Check out the `override `method: https://github.com/sdgluck/mewt/blob/master/index.js#L15

**Comment by sscotth** [comment]
I think I understand where we are getting confused. We weren't coming from the same angle as that is an API design choice.
