### ISSUE TITLE
Array filter, map, concat, slice and reverse, sort, splice?

### ISSUE THREAD

**Issue by bali182** [sdgluck/mewt#6]
Just an idea but this is how it would feel truly intuitive to use this - note that I only mention prototype methods that return new/mutated arrays:

Methods that doesn't mutate arrays like

- `filter`
- `map`
- `concat`
- `slice`

called on `mewt` wrapped arrays should return a new `mewt` wrapped array.

Methods that _do_ mutate the arrays, like

- `reverse`
- `sort`
- `splice`

called on `mewt` wrapped arrays should first `clone` it then return a `mewt` wrapped array.

**Comment by sdgluck** [comment]
I agree this would be the ideal behaviour. I'd be happy to accept a PR if you would like to implement it! (Keeping in mind the <1kb constraint.) Otherwise I'll have a go myself later. 👍

**Comment by sdgluck** [comment]
Also, regarding the 1kb constraint, I am happy to use a minifier (`babili`) if additions like this push the source over the limit.

**Comment by bali182** [comment]
Hmm index.js is at 942 bytes it is a challenging task to make this fit in the 1KB limit 🤔

**Comment by sdgluck** [comment]
I'm about to put in a PR to use babili for minification, so maybe that will help.

**Comment by sdgluck** [comment]
There we go. It's at ~500 bytes minified. 😄  (See #9)

**Comment by bali182** [comment]
![480z480_front_1089_0_0_0_924976b329ccc64f4549635275c37c5f](https://cloud.githubusercontent.com/assets/3879181/24405472/e823fdb0-13bc-11e7-8183-d9de574ed185.jpg)

**Comment by bali182** [comment]
It is pretty nice like this since anyone who needs it for the web can use the minified one and node users can use the regular one. 👍 Or just use the regular one and minify while packaging

**Comment by sdgluck** [comment]
Got this working over at #11. Apologies if you were already working on this. Happy to take your contribution over my own PR if that's the case. 👍 Let me know.

**Comment by bali182** [comment]
Oh wow... Just submitted a PR with this and a bit more, please also check that one! :) It's probably easier to review commit by commit

**Comment by sdgluck** [comment]
fixed in #12
